#!/usr/bin/env bash
# Regenerate the checked-in BES encoding types from xb-encoding.xsd.
#
# Usage: scripts/regenerate-bes-types.sh [build-dir]
#
# The build directory must contain a built xb binary.
# Defaults to build-clang-20.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
BUILD_DIR="${1:-build-clang-20}"
XB_BIN="$PROJECT_DIR/$BUILD_DIR/src/bin/Release/xb"

if [ ! -x "$XB_BIN" ]; then
  echo "error: xb binary not found at $XB_BIN" >&2
  echo "Build the project first: cmake --build $BUILD_DIR --config Release" >&2
  exit 1
fi

TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

"$XB_BIN" generate \
  --header-only \
  -t "$PROJECT_DIR/schema/xb-encoding-typemap.xml" \
  -n "http://xb.dev/encoding=xb::bes" \
  -o "$TMPDIR" \
  "$PROJECT_DIR/schema/xb-encoding.xsd"

TARGET="$PROJECT_DIR/src/include/xb/wire/encoding.hpp"

{
  echo '// Generated from schema/xb-encoding.xsd by xb generate.'
  echo '// DO NOT EDIT — regenerate with: scripts/regenerate-bes-types.sh'
  echo '//'
  echo '// Bootstrap: The xb CLI needs these types to parse BES documents,'
  echo '// but the types are generated by the xb CLI. This checked-in copy'
  echo '// breaks the cycle. The test suite validates it stays in sync with'
  echo '// the schema by independently generating and testing the same types.'
  echo ''
  cat "$TMPDIR/encoding.hpp"
} > "$TARGET"

echo "Regenerated $TARGET ($(wc -l < "$TARGET") lines)"
