// GCC 12 emits a false -Wmaybe-uninitialized for std::variant at -O3.
#if defined(__GNUC__) && !defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmaybe-uninitialized"
#endif

#include "typemap.hpp" // generated by xb_generate_cpp() from fetched schemas

#include <catch2/catch_test_macros.hpp>

TEST_CASE("xb_fetch_schemas: fetched schemas chain with xb_generate_cpp()",
          "[cmake][fetch]") {
  xb::dev::typemap::typemap_type val;
  CHECK(val.mapping.empty());
}
