// GCC 12 emits a false -Wmaybe-uninitialized for std::variant at -O3.
#if defined(__GNUC__) && !defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmaybe-uninitialized"
#endif

#include "typemap.hpp" // generated by xb_add_library()

#include <catch2/catch_test_macros.hpp>

TEST_CASE("xb_add_library: generated types are usable without manual xb link",
          "[cmake][add_library]") {
  xb::dev::typemap::typemap_type val;
  CHECK(val.mapping.empty());
}
