#include "typemap.hpp" // generated by xb_add_library()

#include <catch2/catch_test_macros.hpp>

TEST_CASE("xb_add_library: generated types are usable without manual xb link",
          "[cmake][add_library]") {
  typemap::typemap_type val;
  CHECK(val.mapping.empty());
}
