// GCC 12 emits a false -Wmaybe-uninitialized for std::variant at -O3.
#if defined(__GNUC__) && !defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmaybe-uninitialized"
#endif

#include "typemap.hpp" // generated by xb_generate_cpp() in SPLIT mode

#include <catch2/catch_test_macros.hpp>

TEST_CASE("split mode: generated types from xb_generate_cpp() are usable",
          "[cmake][split]") {
  xb::dev::typemap::typemap_type val;
  CHECK(val.mapping.empty());
}
