#include "typemap.hpp" // generated by xb_generate_cpp() in SPLIT mode

#include <catch2/catch_test_macros.hpp>

TEST_CASE("split mode: generated types from xb_generate_cpp() are usable",
          "[cmake][split]") {
  typemap::typemap_type val;
  CHECK(val.mapping.empty());
}
