#include "typemap.hpp" // generated by xb_generate_cpp()

#include <catch2/catch_test_macros.hpp>

TEST_CASE("generated types from xb_generate_cpp() are usable", "[cmake]") {
  typemap::typemap_type val;
  CHECK(val.mapping.empty());
}
