// GCC 12 emits a false -Wmaybe-uninitialized for std::variant containing
// std::unique_ptr in particle::term_type at -O3. Suppress it here.
#if defined(__GNUC__) && !defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmaybe-uninitialized"
#endif

#include "lexer.hpp" // generated by xb_generate_cpp() with pascal type naming

#include <catch2/catch_test_macros.hpp>

using namespace xeag::org::lexer;

TEST_CASE("xeag-lexer pascal: basic construction",
          "[xeag-lexer][compile][pascal]") {
  LexerType lex;
  MatchType m;
  m.name = "TOKEN";
  m.value = "+";
  lex.match.push_back(std::move(m));

  REQUIRE(lex.match.size() == 1);
  CHECK(lex.match[0].name == "TOKEN");
}
