#include "lexer.hpp" // generated by xb_generate_cpp() with pascal type naming

#include <catch2/catch_test_macros.hpp>

using namespace lexer;

TEST_CASE("xeag-lexer pascal: basic construction",
          "[xeag-lexer][compile][pascal]") {
  LexerType lex;
  MatchType m;
  m.name = "TOKEN";
  m.value = "+";
  lex.match.push_back(std::move(m));

  REQUIRE(lex.match.size() == 1);
  CHECK(lex.match[0].name == "TOKEN");
}
