#include "lexer.hpp" // generated by xb_generate_cpp() in SPLIT + wrapped mode

#include <xb/expat_reader.hpp>
#include <xb/ostream_writer.hpp>

#include <catch2/catch_test_macros.hpp>

#include <sstream>
#include <string>

using namespace lexer;

// =========================================================================
// Construction tests
// =========================================================================

TEST_CASE("xeag-lexer wrapped: basic construction",
          "[xeag-lexer][compile][wrapped][file-per-type]") {
  lexer_type lex;
  match_type m;
  m.set_name("TOKEN");
  m.set_value("+");
  lex.match_push_back(std::move(m));

  REQUIRE(lex.match_size() == 1);
  CHECK(lex.match(0).name() == "TOKEN");
}

TEST_CASE("xeag-lexer wrapped: nested recursive construction",
          "[xeag-lexer][compile][wrapped][file-per-type]") {
  // Build: group { choice { option { literal "a" }, option { literal "b" } } }
  pattern_literal_type lit_a;
  lit_a.set_value("a");

  pattern_literal_type lit_b;
  lit_b.set_value("b");

  pattern_group_type opt_a;
  opt_a.choice_push_back(pattern_group_type_data::choice_element_type{lit_a});

  pattern_group_type opt_b;
  opt_b.choice_push_back(pattern_group_type_data::choice_element_type{lit_b});

  pattern_choice_type choice;
  choice.option_push_back(
      std::make_unique<pattern_group_type>(std::move(opt_a)));
  choice.option_push_back(
      std::make_unique<pattern_group_type>(std::move(opt_b)));

  pattern_group_type outer;
  outer.choice_push_back(pattern_group_type_data::choice_element_type{
      std::make_unique<pattern_choice_type>(std::move(choice))});
  outer.set_repetition(repetition_type::zero_or_more);

  match_type m;
  m.set_name("TOKEN");
  m.choice_push_back(match_type_data::choice_element_type{
      std::make_unique<pattern_group_type>(std::move(outer))});

  lexer_type lex;
  lex.match_push_back(std::move(m));

  CHECK(lex.match_size() == 1);
}

// =========================================================================
// Round-trip serialization tests
// =========================================================================

TEST_CASE("xeag-lexer wrapped: round-trip simple lexer",
          "[xeag-lexer][round-trip][wrapped][file-per-type]") {
  std::string xml = R"XML(<?xml version="1.0"?>
<lexer xmlns="http://xeag.org/lexer">
  <skip chars=" &#10;&#9;" repetition="one-or-more"/>
  <match name="PLUS" value="+"/>
  <match name="MINUS" value="-"/>
  <match name="NUMBER" chars="0-9" repetition="one-or-more"/>
</lexer>
)XML";

  // Read
  xb::expat_reader reader(xml);
  reader.read();
  auto lex = read_lexer_type(reader);

  REQUIRE(lex.skip_size() == 1);
  REQUIRE(lex.match_size() == 3);
  CHECK(lex.match(0).name() == "PLUS");
  CHECK(lex.match(0).value().has_value());
  CHECK(*lex.match(0).value() == "+");
  CHECK(lex.match(2).name() == "NUMBER");
  CHECK(lex.match(2).chars().has_value());
  CHECK(*lex.match(2).chars() == "0-9");
  CHECK(lex.match(2).repetition().has_value());
  CHECK(*lex.match(2).repetition() == repetition_type::one_or_more);

  // Write
  std::ostringstream oss;
  xb::ostream_writer writer(oss);
  writer.start_element(xb::qname{"http://xeag.org/lexer", "lexer"});
  writer.namespace_declaration("", "http://xeag.org/lexer");
  write_lexer_type(lex, writer);
  writer.end_element();

  // Re-read
  xb::expat_reader reader2(oss.str());
  reader2.read();
  auto lex2 = read_lexer_type(reader2);

  // Verify round-trip
  CHECK(lex2.skip_size() == lex.skip_size());
  CHECK(lex2.match_size() == lex.match_size());
  CHECK(lex2.match(0).name() == lex.match(0).name());
  CHECK(lex2.match(0).value() == lex.match(0).value());
  CHECK(lex2.match(2).name() == lex.match(2).name());
  CHECK(lex2.match(2).chars() == lex.match(2).chars());
  CHECK(lex2.match(2).repetition() == lex.match(2).repetition());
}

TEST_CASE("xeag-lexer wrapped: round-trip complex pattern",
          "[xeag-lexer][round-trip][wrapped][file-per-type]") {
  std::string xml = R"XML(<?xml version="1.0"?>
<lexer xmlns="http://xeag.org/lexer">
  <skip chars=" &#10;&#9;&#13;" repetition="one-or-more"/>
  <skip>
    <literal value="/*"/>
    <char-class chars="*" complement="true" repetition="zero-or-more"/>
    <literal value="*/"/>
  </skip>
  <match name="IDENT">
    <char-class chars="a-zA-Z_"/>
    <char-class chars="a-zA-Z0-9_" repetition="zero-or-more"/>
  </match>
  <match name="NUMBER">
    <choice>
      <option>
        <char-class chars="0-9" repetition="one-or-more"/>
        <group repetition="optional">
          <literal value="."/>
          <char-class chars="0-9" repetition="one-or-more"/>
        </group>
      </option>
      <option>
        <literal value="."/>
        <char-class chars="0-9" repetition="one-or-more"/>
      </option>
    </choice>
  </match>
  <match name="EQUALS" value="="/>
  <match name="SEMI" value=";"/>
</lexer>
)XML";

  xb::expat_reader reader(xml);
  reader.read();
  auto lex = read_lexer_type(reader);

  REQUIRE(lex.skip_size() == 2);
  REQUIRE(lex.match_size() == 4);
  CHECK(lex.skip(1).choice_size() == 3);
  CHECK(lex.match(0).name() == "IDENT");
  CHECK(lex.match(0).choice_size() == 2);
  CHECK(lex.match(1).name() == "NUMBER");
  CHECK(lex.match(1).choice_size() == 1);

  // Write and re-read
  std::ostringstream oss;
  xb::ostream_writer writer(oss);
  writer.start_element(xb::qname{"http://xeag.org/lexer", "lexer"});
  writer.namespace_declaration("", "http://xeag.org/lexer");
  write_lexer_type(lex, writer);
  writer.end_element();

  xb::expat_reader reader2(oss.str());
  reader2.read();
  auto lex2 = read_lexer_type(reader2);

  CHECK(lex2.skip_size() == 2);
  CHECK(lex2.match_size() == 4);
  CHECK(lex2.match(0).name() == "IDENT");
  CHECK(lex2.match(1).name() == "NUMBER");
  CHECK(lex2.match(0).choice_size() == 2);
  CHECK(lex2.match(1).choice_size() == 1);
  CHECK(lex2.skip(1).choice_size() == 3);
}

TEST_CASE("xeag-lexer wrapped: round-trip deeply nested groups",
          "[xeag-lexer][round-trip][wrapped][file-per-type]") {
  std::string xml = R"XML(<?xml version="1.0"?>
<lexer xmlns="http://xeag.org/lexer">
  <match name="NESTED">
    <group>
      <literal value="("/>
      <group repetition="zero-or-more">
        <choice>
          <option>
            <char-class chars="a-z"/>
          </option>
          <option>
            <group>
              <literal value="["/>
              <char-class chars="0-9" repetition="one-or-more"/>
              <literal value="]"/>
            </group>
          </option>
        </choice>
      </group>
      <literal value=")"/>
    </group>
  </match>
</lexer>
)XML";

  xb::expat_reader reader(xml);
  reader.read();
  auto lex = read_lexer_type(reader);

  REQUIRE(lex.match_size() == 1);
  CHECK(lex.match(0).name() == "NESTED");

  // Write and re-read
  std::ostringstream oss;
  xb::ostream_writer writer(oss);
  writer.start_element(xb::qname{"http://xeag.org/lexer", "lexer"});
  writer.namespace_declaration("", "http://xeag.org/lexer");
  write_lexer_type(lex, writer);
  writer.end_element();

  xb::expat_reader reader2(oss.str());
  reader2.read();
  auto lex2 = read_lexer_type(reader2);

  CHECK(lex2.match_size() == 1);
  CHECK(lex2.match(0).name() == "NESTED");
  CHECK(lex2.match(0).choice_size() == 1);
}
