// GCC 12 emits a false -Wmaybe-uninitialized for std::variant containing
// std::unique_ptr in particle::term_type at -O3. Suppress it here.
#if defined(__GNUC__) && !defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmaybe-uninitialized"
#endif

#include "lexer.hpp" // generated by xb_generate_cpp() in HEADER_ONLY mode

#include <catch2/catch_test_macros.hpp>

#include <string>

using namespace xeag::org::lexer;

TEST_CASE("xeag-lexer header-only: basic construction",
          "[xeag-lexer][compile][header-only]") {
  lexer_type lex;
  match_type m;
  m.name = "X";
  m.value = "x";
  lex.match.push_back(std::move(m));

  REQUIRE(lex.match.size() == 1);
  CHECK(lex.match[0].name == "X");
}
