// Generated from schema/xb-encoding.xsd by xb generate.
// DO NOT EDIT — regenerate with: scripts/regenerate-bes-types.sh
//
// Bootstrap: The xb CLI needs these types to parse BES documents,
// but the types are generated by the xb CLI. This checked-in copy
// breaks the cycle. The test suite validates it stays in sync with
// the schema by independently generating and testing the same types.

#pragma once

#include <memory>
#include <optional>
#include <stdexcept>
#include <string>
#include <string_view>
#include <variant>
#include <vector>

#include "xb/xml_io.hpp"
#include "xb/xml_reader.hpp"
#include "xb/xml_value.hpp"
#include "xb/xml_writer.hpp"

namespace xb::bes {

  struct group_type;

  struct choice_type;

  struct alternative_type;

  struct repeat_type;

  struct choice_type;

  struct group_type;

  struct alternative_type;

  struct repeat_type;

  struct group_type;

  struct choice_type;

  struct alternative_type;

  struct repeat_type;

  enum class byte_order_type {
    big_endian,
    little_endian,
    native,
  };

  inline std::string_view
  to_string(byte_order_type v) {
    switch (v) {
      case byte_order_type::big_endian:
        return "big-endian";
      case byte_order_type::little_endian:
        return "little-endian";
      case byte_order_type::native:
        return "native";
    }
    return "";
  }

  inline byte_order_type
  byte_order_type_from_string(std::string_view s) {
    if (s == "big-endian") return byte_order_type::big_endian;
    if (s == "little-endian") return byte_order_type::little_endian;
    if (s == "native") return byte_order_type::native;
    throw std::invalid_argument(std::string("invalid byte_order_type value: ") +
                                std::string(s));
  }

  enum class bit_order_type {
    msb_first,
    lsb_first,
  };

  inline std::string_view
  to_string(bit_order_type v) {
    switch (v) {
      case bit_order_type::msb_first:
        return "msb-first";
      case bit_order_type::lsb_first:
        return "lsb-first";
    }
    return "";
  }

  inline bit_order_type
  bit_order_type_from_string(std::string_view s) {
    if (s == "msb-first") return bit_order_type::msb_first;
    if (s == "lsb-first") return bit_order_type::lsb_first;
    throw std::invalid_argument(std::string("invalid bit_order_type value: ") +
                                std::string(s));
  }

  enum class primitive_encoding_type {
    unsigned_,
    twos_complement,
    bcd,
    ascii_decimal,
    ieee754,
    fixed_point,
    ascii,
    utf8,
    utf16,
    raw,
    boolean,
    enum_integer,
    enum_char,
    bitset,
    epoch,
    epoch_millis,
    epoch_micros,
    epoch_nanos,
    bcd_datetime,
  };

  inline std::string_view
  to_string(primitive_encoding_type v) {
    switch (v) {
      case primitive_encoding_type::unsigned_:
        return "unsigned";
      case primitive_encoding_type::twos_complement:
        return "twos-complement";
      case primitive_encoding_type::bcd:
        return "bcd";
      case primitive_encoding_type::ascii_decimal:
        return "ascii-decimal";
      case primitive_encoding_type::ieee754:
        return "ieee754";
      case primitive_encoding_type::fixed_point:
        return "fixed-point";
      case primitive_encoding_type::ascii:
        return "ascii";
      case primitive_encoding_type::utf8:
        return "utf8";
      case primitive_encoding_type::utf16:
        return "utf16";
      case primitive_encoding_type::raw:
        return "raw";
      case primitive_encoding_type::boolean:
        return "boolean";
      case primitive_encoding_type::enum_integer:
        return "enum-integer";
      case primitive_encoding_type::enum_char:
        return "enum-char";
      case primitive_encoding_type::bitset:
        return "bitset";
      case primitive_encoding_type::epoch:
        return "epoch";
      case primitive_encoding_type::epoch_millis:
        return "epoch-millis";
      case primitive_encoding_type::epoch_micros:
        return "epoch-micros";
      case primitive_encoding_type::epoch_nanos:
        return "epoch-nanos";
      case primitive_encoding_type::bcd_datetime:
        return "bcd-datetime";
    }
    return "";
  }

  inline primitive_encoding_type
  primitive_encoding_type_from_string(std::string_view s) {
    if (s == "unsigned") return primitive_encoding_type::unsigned_;
    if (s == "twos-complement") return primitive_encoding_type::twos_complement;
    if (s == "bcd") return primitive_encoding_type::bcd;
    if (s == "ascii-decimal") return primitive_encoding_type::ascii_decimal;
    if (s == "ieee754") return primitive_encoding_type::ieee754;
    if (s == "fixed-point") return primitive_encoding_type::fixed_point;
    if (s == "ascii") return primitive_encoding_type::ascii;
    if (s == "utf8") return primitive_encoding_type::utf8;
    if (s == "utf16") return primitive_encoding_type::utf16;
    if (s == "raw") return primitive_encoding_type::raw;
    if (s == "boolean") return primitive_encoding_type::boolean;
    if (s == "enum-integer") return primitive_encoding_type::enum_integer;
    if (s == "enum-char") return primitive_encoding_type::enum_char;
    if (s == "bitset") return primitive_encoding_type::bitset;
    if (s == "epoch") return primitive_encoding_type::epoch;
    if (s == "epoch-millis") return primitive_encoding_type::epoch_millis;
    if (s == "epoch-micros") return primitive_encoding_type::epoch_micros;
    if (s == "epoch-nanos") return primitive_encoding_type::epoch_nanos;
    if (s == "bcd-datetime") return primitive_encoding_type::bcd_datetime;
    throw std::invalid_argument(
        std::string("invalid primitive_encoding_type value: ") +
        std::string(s));
  }

  enum class padding_type {
    space,
    null,
    zero,
  };

  inline std::string_view
  to_string(padding_type v) {
    switch (v) {
      case padding_type::space:
        return "space";
      case padding_type::null:
        return "null";
      case padding_type::zero:
        return "zero";
    }
    return "";
  }

  inline padding_type
  padding_type_from_string(std::string_view s) {
    if (s == "space") return padding_type::space;
    if (s == "null") return padding_type::null;
    if (s == "zero") return padding_type::zero;
    throw std::invalid_argument(std::string("invalid padding_type value: ") +
                                std::string(s));
  }

  enum class charset_type {
    ascii,
    utf8,
    utf16_be,
    utf16_le,
  };

  inline std::string_view
  to_string(charset_type v) {
    switch (v) {
      case charset_type::ascii:
        return "ascii";
      case charset_type::utf8:
        return "utf8";
      case charset_type::utf16_be:
        return "utf16-be";
      case charset_type::utf16_le:
        return "utf16-le";
    }
    return "";
  }

  inline charset_type
  charset_type_from_string(std::string_view s) {
    if (s == "ascii") return charset_type::ascii;
    if (s == "utf8") return charset_type::utf8;
    if (s == "utf16-be") return charset_type::utf16_be;
    if (s == "utf16-le") return charset_type::utf16_le;
    throw std::invalid_argument(std::string("invalid charset_type value: ") +
                                std::string(s));
  }

  enum class length_includes_type {
    header,
    payload,
  };

  inline std::string_view
  to_string(length_includes_type v) {
    switch (v) {
      case length_includes_type::header:
        return "header";
      case length_includes_type::payload:
        return "payload";
    }
    return "";
  }

  inline length_includes_type
  length_includes_type_from_string(std::string_view s) {
    if (s == "header") return length_includes_type::header;
    if (s == "payload") return length_includes_type::payload;
    throw std::invalid_argument(
        std::string("invalid length_includes_type value: ") + std::string(s));
  }

  enum class length_unit_type {
    bits,
    bytes,
  };

  inline std::string_view
  to_string(length_unit_type v) {
    switch (v) {
      case length_unit_type::bits:
        return "bits";
      case length_unit_type::bytes:
        return "bytes";
    }
    return "";
  }

  inline length_unit_type
  length_unit_type_from_string(std::string_view s) {
    if (s == "bits") return length_unit_type::bits;
    if (s == "bytes") return length_unit_type::bytes;
    throw std::invalid_argument(
        std::string("invalid length_unit_type value: ") + std::string(s));
  }

  enum class repeat_until_type {
    end_of_payload,
  };

  inline std::string_view
  to_string(repeat_until_type v) {
    switch (v) {
      case repeat_until_type::end_of_payload:
        return "end-of-payload";
    }
    return "";
  }

  inline repeat_until_type
  repeat_until_type_from_string(std::string_view s) {
    if (s == "end-of-payload") return repeat_until_type::end_of_payload;
    throw std::invalid_argument(
        std::string("invalid repeat_until_type value: ") + std::string(s));
  }

  enum class enum_encode_by_type {
    value,
    ordinal,
  };

  inline std::string_view
  to_string(enum_encode_by_type v) {
    switch (v) {
      case enum_encode_by_type::value:
        return "value";
      case enum_encode_by_type::ordinal:
        return "ordinal";
    }
    return "";
  }

  inline enum_encode_by_type
  enum_encode_by_type_from_string(std::string_view s) {
    if (s == "value") return enum_encode_by_type::value;
    if (s == "ordinal") return enum_encode_by_type::ordinal;
    throw std::invalid_argument(
        std::string("invalid enum_encode_by_type value: ") + std::string(s));
  }

  struct import_type {
    std::string href{};

    bool
    operator==(const struct import_type&) const = default;
  };

  struct layer_type {
    using match_type = std::optional<std::string>;
    using value_type = std::optional<std::string>;
    std::string ref{};
    match_type match{};
    value_type value{};

    bool
    operator==(const struct layer_type&) const = default;
  };

  struct selector_type {
    using qname_type = std::optional<std::string>;
    using path_type = std::optional<std::string>;
    using type_type = std::optional<std::string>;
    using namespace__type = std::optional<std::string>;
    using attribute_type = std::optional<std::string>;
    qname_type qname{};
    path_type path{};
    type_type type{};
    namespace__type namespace_{};
    attribute_type attribute{};

    bool
    operator==(const struct selector_type&) const = default;
  };

  struct padding_field_type {
    using bits_type = std::optional<unsigned>;
    using align_to_type = std::optional<unsigned>;
    using fill_type = std::optional<std::string>;
    bits_type bits{};
    align_to_type align_to{};
    fill_type fill = "0x00";

    bool
    operator==(const struct padding_field_type&) const = default;
  };

  struct constant_type {
    using type_type = std::optional<std::string>;
    std::string name{};
    type_type type{};
    std::string value{};

    bool
    operator==(const struct constant_type&) const = default;
  };

  struct choice_type {
    std::vector<std::unique_ptr<alternative_type>> alternative{};
    std::string name{};
    std::string discriminant_field{};

    bool
    operator==(const struct choice_type&) const = default;
  };

  struct discriminant_type {
    std::string field{};

    bool
    operator==(const struct discriminant_type&) const = default;
  };

  struct save_position_type {
    std::string name{};

    bool
    operator==(const struct save_position_type&) const = default;
  };

  struct payload_type {
    using length_field_type = std::optional<std::string>;
    length_field_type length_field{};

    bool
    operator==(const struct payload_type&) const = default;
  };

  struct present_when_type {
    using expr_type = std::optional<std::string>;
    using field_type = std::optional<std::string>;
    using field_equals_type = std::optional<std::string>;
    expr_type expr{};
    field_type field{};
    field_equals_type field_equals{};

    bool
    operator==(const struct present_when_type&) const = default;
  };

  struct transform_type {
    using header_type = std::optional<std::string>;
    std::string encode{};
    std::string decode{};
    header_type header{};

    bool
    operator==(const struct transform_type&) const = default;
  };

  struct enum_entry_type {
    std::string xsd_value{};
    std::string wire_value{};

    bool
    operator==(const struct enum_entry_type&) const = default;
  };

  struct delimiter_type {
    using escape_type = std::optional<std::string>;
    using escape_xor_type = std::optional<std::string>;
    std::string value{};
    escape_type escape{};
    escape_xor_type escape_xor{};

    bool
    operator==(const struct delimiter_type&) const = default;
  };

  struct computed_field_type {
    using seed_type = std::optional<std::string>;
    using seed_expr_type = std::optional<std::string>;
    std::string name{};
    unsigned bits{};
    std::string algorithm{};
    std::string over{};
    std::optional<byte_order_type> byte_order{};
    seed_type seed{};
    seed_expr_type seed_expr{};

    bool
    operator==(const struct computed_field_type&) const = default;
  };

  struct wire_field_type {
    using encoding_type = std::optional<primitive_encoding_type>;
    using value_type = std::optional<std::string>;
    std::string name{};
    unsigned bits{};
    encoding_type encoding{};
    std::optional<byte_order_type> byte_order{};
    value_type value{};

    bool
    operator==(const struct wire_field_type&) const = default;
  };

  struct defaults_type {
    using alignment_type = std::optional<unsigned>;
    using string_padding_type = std::optional<padding_type>;
    using string_encoding_type = std::optional<charset_type>;
    std::optional<byte_order_type> byte_order{};
    std::optional<bit_order_type> bit_order{};
    alignment_type alignment = 8;
    string_padding_type string_padding{};
    string_encoding_type string_encoding{};

    bool
    operator==(const struct defaults_type&) const = default;
  };

  struct string_encoding_type {
    using terminator_type = std::optional<std::string>;
    using length_field_type = std::optional<std::string>;
    std::optional<charset_type> charset{};
    std::optional<padding_type> padding{};
    terminator_type terminator{};
    length_field_type length_field{};

    bool
    operator==(const struct string_encoding_type&) const = default;
  };

  struct length_type {
    using includes_type = std::optional<length_includes_type>;
    using unit_type = std::optional<length_unit_type>;
    using adjust_type = std::optional<int>;
    std::string field{};
    includes_type includes{};
    unit_type unit{};
    adjust_type adjust{};

    bool
    operator==(const struct length_type&) const = default;
  };

  struct frame_stack_type {
    std::vector<layer_type> layer{};
    std::string name{};

    bool
    operator==(const struct frame_stack_type&) const = default;
  };

  struct enum_map_type {
    using entry_type = std::vector<enum_entry_type>;
    using encode_by_type = std::optional<enum_encode_by_type>;
    entry_type entry{};
    encode_by_type encode_by{};

    bool
    operator==(const struct enum_map_type&) const = default;
  };

  struct dimension_type {
    using block_length_field_type = std::optional<std::string>;
    std::vector<wire_field_type> wire_field{};
    std::string count_field{};
    block_length_field_type block_length_field{};

    bool
    operator==(const struct dimension_type&) const = default;
  };

  struct field_type {
    using type_type = std::optional<std::string>;
    using encoding_type = std::optional<primitive_encoding_type>;
    using offset_type = std::optional<unsigned>;
    using null_value_type = std::optional<std::string>;
    using size_type = std::optional<std::string>;
    std::optional<present_when_type> present_when{};
    std::optional<string_encoding_type> string_encoding{};
    std::optional<transform_type> transform{};
    std::optional<enum_map_type> enum_map{};
    std::string name{};
    unsigned bits{};
    type_type type{};
    encoding_type encoding{};
    std::optional<byte_order_type> byte_order{};
    offset_type offset{};
    null_value_type null_value{};
    size_type size{};

    bool
    operator==(const struct field_type&) const = default;
  };

  struct framing_type {
    using choice_element_type =
        std::variant<field_type, padding_field_type, length_type,
                     discriminant_type, delimiter_type, save_position_type,
                     computed_field_type, std::unique_ptr<repeat_type>,
                     payload_type>;
    using choice_type = std::vector<choice_element_type>;
    choice_type choice{};
    std::string name{};
    std::optional<byte_order_type> byte_order{};
    std::optional<bit_order_type> bit_order{};

    bool
    operator==(const struct framing_type&) const = default;
  };

  struct extensions_type {
    std::vector<std::variant<field_type, padding_field_type, constant_type,
                             wire_field_type, std::unique_ptr<group_type>,
                             std::unique_ptr<choice_type>, length_type,
                             discriminant_type, save_position_type,
                             computed_field_type, std::unique_ptr<repeat_type>>>
        choice{};

    bool
    operator==(const struct extensions_type&) const = default;
  };

  struct group_type {
    using count_field_type = std::optional<std::string>;
    using block_length_field_type = std::optional<std::string>;
    std::optional<dimension_type> dimension{};
    std::vector<std::variant<field_type, padding_field_type, constant_type,
                             wire_field_type, std::unique_ptr<group_type>,
                             std::unique_ptr<choice_type>, length_type,
                             discriminant_type, save_position_type,
                             computed_field_type, std::unique_ptr<repeat_type>>>
        choice{};
    std::string name{};
    count_field_type count_field{};
    block_length_field_type block_length_field{};

    bool
    operator==(const struct group_type&) const = default;
  };

  struct alternative_type {
    std::vector<std::variant<field_type, padding_field_type, constant_type,
                             wire_field_type, std::unique_ptr<group_type>,
                             std::unique_ptr<choice_type>, length_type,
                             discriminant_type, save_position_type,
                             computed_field_type, std::unique_ptr<repeat_type>>>
        choice{};
    std::string name{};
    std::string discriminant_value{};

    bool
    operator==(const struct alternative_type&) const = default;
  };

  struct repeat_type {
    using choice_element_type =
        std::variant<field_type, padding_field_type, length_type,
                     discriminant_type, delimiter_type, save_position_type,
                     computed_field_type, std::unique_ptr<repeat_type>,
                     payload_type>;
    using choice_type = std::vector<choice_element_type>;
    using count_field_type = std::optional<std::string>;
    using element_size_field_type = std::optional<std::string>;
    using fixed_size_type = std::optional<unsigned>;
    using until_type = std::optional<repeat_until_type>;
    using until_delimiter_type = std::optional<std::string>;
    choice_type choice{};
    count_field_type count_field{};
    element_size_field_type element_size_field{};
    fixed_size_type fixed_size{};
    until_type until{};
    until_delimiter_type until_delimiter{};

    bool
    operator==(const struct repeat_type&) const = default;
  };

  struct message_type {
    using type_type = std::optional<std::string>;
    using discriminant_value_type = std::optional<std::string>;
    using framing_type = std::optional<std::string>;
    using frame_stack_type = std::optional<std::string>;
    std::optional<selector_type> selector{};
    std::vector<std::variant<field_type, padding_field_type, constant_type,
                             wire_field_type, std::unique_ptr<group_type>,
                             std::unique_ptr<choice_type>, length_type,
                             discriminant_type, save_position_type,
                             computed_field_type, std::unique_ptr<repeat_type>>>
        choice{};
    std::optional<extensions_type> extensions{};
    std::string name{};
    type_type type{};
    discriminant_value_type discriminant_value{};
    framing_type framing{};
    frame_stack_type frame_stack{};
    std::optional<byte_order_type> byte_order{};
    std::optional<bit_order_type> bit_order{};

    bool
    operator==(const struct message_type&) const = default;
  };

  struct encoding_type {
    using choice_element_type =
        std::variant<framing_type, frame_stack_type, message_type>;
    using choice_type = std::vector<choice_element_type>;
    using target_namespace_type = std::optional<std::string>;
    using target_schema_type = std::optional<std::string>;
    std::optional<defaults_type> defaults{};
    std::vector<import_type> import{};
    choice_type choice{};
    target_namespace_type target_namespace{};
    target_schema_type target_schema{};

    bool
    operator==(const struct encoding_type&) const = default;
  };

  group_type
  read_group_type(xb::xml_reader& reader);
  void
  write_group_type(const group_type& value, xb::xml_writer& writer);
  choice_type
  read_choice_type(xb::xml_reader& reader);
  void
  write_choice_type(const choice_type& value, xb::xml_writer& writer);
  alternative_type
  read_alternative_type(xb::xml_reader& reader);
  void
  write_alternative_type(const alternative_type& value, xb::xml_writer& writer);
  repeat_type
  read_repeat_type(xb::xml_reader& reader);
  void
  write_repeat_type(const repeat_type& value, xb::xml_writer& writer);
  import_type
  read_import_type(xb::xml_reader& reader);
  void
  write_import_type(const import_type& value, xb::xml_writer& writer);
  layer_type
  read_layer_type(xb::xml_reader& reader);
  void
  write_layer_type(const layer_type& value, xb::xml_writer& writer);
  selector_type
  read_selector_type(xb::xml_reader& reader);
  void
  write_selector_type(const selector_type& value, xb::xml_writer& writer);
  padding_field_type
  read_padding_field_type(xb::xml_reader& reader);
  void
  write_padding_field_type(const padding_field_type& value,
                           xb::xml_writer& writer);
  constant_type
  read_constant_type(xb::xml_reader& reader);
  void
  write_constant_type(const constant_type& value, xb::xml_writer& writer);
  discriminant_type
  read_discriminant_type(xb::xml_reader& reader);
  void
  write_discriminant_type(const discriminant_type& value,
                          xb::xml_writer& writer);
  save_position_type
  read_save_position_type(xb::xml_reader& reader);
  void
  write_save_position_type(const save_position_type& value,
                           xb::xml_writer& writer);
  payload_type
  read_payload_type(xb::xml_reader& reader);
  void
  write_payload_type(const payload_type& value, xb::xml_writer& writer);
  present_when_type
  read_present_when_type(xb::xml_reader& reader);
  void
  write_present_when_type(const present_when_type& value,
                          xb::xml_writer& writer);
  transform_type
  read_transform_type(xb::xml_reader& reader);
  void
  write_transform_type(const transform_type& value, xb::xml_writer& writer);
  enum_entry_type
  read_enum_entry_type(xb::xml_reader& reader);
  void
  write_enum_entry_type(const enum_entry_type& value, xb::xml_writer& writer);
  delimiter_type
  read_delimiter_type(xb::xml_reader& reader);
  void
  write_delimiter_type(const delimiter_type& value, xb::xml_writer& writer);
  computed_field_type
  read_computed_field_type(xb::xml_reader& reader);
  void
  write_computed_field_type(const computed_field_type& value,
                            xb::xml_writer& writer);
  wire_field_type
  read_wire_field_type(xb::xml_reader& reader);
  void
  write_wire_field_type(const wire_field_type& value, xb::xml_writer& writer);
  defaults_type
  read_defaults_type(xb::xml_reader& reader);
  void
  write_defaults_type(const defaults_type& value, xb::xml_writer& writer);
  string_encoding_type
  read_string_encoding_type(xb::xml_reader& reader);
  void
  write_string_encoding_type(const string_encoding_type& value,
                             xb::xml_writer& writer);
  length_type
  read_length_type(xb::xml_reader& reader);
  void
  write_length_type(const length_type& value, xb::xml_writer& writer);
  frame_stack_type
  read_frame_stack_type(xb::xml_reader& reader);
  void
  write_frame_stack_type(const frame_stack_type& value, xb::xml_writer& writer);
  enum_map_type
  read_enum_map_type(xb::xml_reader& reader);
  void
  write_enum_map_type(const enum_map_type& value, xb::xml_writer& writer);
  dimension_type
  read_dimension_type(xb::xml_reader& reader);
  void
  write_dimension_type(const dimension_type& value, xb::xml_writer& writer);
  field_type
  read_field_type(xb::xml_reader& reader);
  void
  write_field_type(const field_type& value, xb::xml_writer& writer);
  framing_type
  read_framing_type(xb::xml_reader& reader);
  void
  write_framing_type(const framing_type& value, xb::xml_writer& writer);
  extensions_type
  read_extensions_type(xb::xml_reader& reader);
  void
  write_extensions_type(const extensions_type& value, xb::xml_writer& writer);
  message_type
  read_message_type(xb::xml_reader& reader);
  void
  write_message_type(const message_type& value, xb::xml_writer& writer);
  encoding_type
  read_encoding_type(xb::xml_reader& reader);
  void
  write_encoding_type(const encoding_type& value, xb::xml_writer& writer);
  bool
  validate_choice_type(const choice_type& value);
  bool
  validate_frame_stack_type(const frame_stack_type& value);
  bool
  validate_enum_map_type(const enum_map_type& value);
  bool
  validate_dimension_type(const dimension_type& value);

  inline group_type
  read_group_type(xb::xml_reader& reader) {
    group_type result;
    result.name =
        xb::parse<std::string>(reader.attribute_value(xb::qname{"", "name"}));
    {
      auto attr_val__ = reader.attribute_value(xb::qname{"", "count-field"});
      if (!attr_val__.empty()) {
        result.count_field = xb::parse<std::string>(attr_val__);
      }
    }
    {
      auto attr_val__ =
          reader.attribute_value(xb::qname{"", "block-length-field"});
      if (!attr_val__.empty()) {
        result.block_length_field = xb::parse<std::string>(attr_val__);
      }
    }
    auto start_depth = reader.depth();
    while (reader.read()) {
      if (reader.node_type() == xb::xml_node_type::end_element &&
          reader.depth() == start_depth)
        break;
      if (reader.node_type() != xb::xml_node_type::start_element) continue;
      auto& name = reader.name();
      if (name == xb::qname{"http://xb.dev/encoding", "dimension"}) {
        result.dimension = read_dimension_type(reader);
      } else if (name == xb::qname{"http://xb.dev/encoding", "field"}) {
        result.choice.push_back(read_field_type(reader));
      } else if (name == xb::qname{"http://xb.dev/encoding", "padding"}) {
        result.choice.push_back(read_padding_field_type(reader));
      } else if (name == xb::qname{"http://xb.dev/encoding", "constant"}) {
        result.choice.push_back(read_constant_type(reader));
      } else if (name == xb::qname{"http://xb.dev/encoding", "wire-field"}) {
        result.choice.push_back(read_wire_field_type(reader));
      } else if (name == xb::qname{"http://xb.dev/encoding", "group"}) {
        result.choice.push_back(
            std::make_unique<group_type>(read_group_type(reader)));
      } else if (name == xb::qname{"http://xb.dev/encoding", "choice"}) {
        result.choice.push_back(
            std::make_unique<choice_type>(read_choice_type(reader)));
      } else if (name == xb::qname{"http://xb.dev/encoding", "length"}) {
        result.choice.push_back(read_length_type(reader));
      } else if (name == xb::qname{"http://xb.dev/encoding", "discriminant"}) {
        result.choice.push_back(read_discriminant_type(reader));
      } else if (name == xb::qname{"http://xb.dev/encoding", "save-position"}) {
        result.choice.push_back(read_save_position_type(reader));
      } else if (name ==
                 xb::qname{"http://xb.dev/encoding", "computed-field"}) {
        result.choice.push_back(read_computed_field_type(reader));
      } else if (name == xb::qname{"http://xb.dev/encoding", "repeat"}) {
        result.choice.push_back(
            std::make_unique<repeat_type>(read_repeat_type(reader)));
      } else {
        xb::skip_element(reader);
      }
    }
    return result;
  }

  inline void
  write_group_type(const group_type& value, xb::xml_writer& writer) {
    writer.attribute(xb::qname{"", "name"}, xb::format(value.name));
    if (value.count_field) {
      writer.attribute(xb::qname{"", "count-field"},
                       xb::format(*value.count_field));
    }
    if (value.block_length_field) {
      writer.attribute(xb::qname{"", "block-length-field"},
                       xb::format(*value.block_length_field));
    }
    if (value.dimension) {
      writer.start_element(xb::qname{"http://xb.dev/encoding", "dimension"});
      write_dimension_type(*value.dimension, writer);
      writer.end_element();
    }
    for (const auto& choice_item : value.choice) {
      std::visit(
          [&](const auto& v) {
            using T = std::decay_t<decltype(v)>;
            if constexpr (std::is_same_v<T, field_type>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "field"});
              write_field_type(v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T, padding_field_type>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "padding"});
              write_padding_field_type(v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T, constant_type>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "constant"});
              write_constant_type(v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T, wire_field_type>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "wire-field"});
              write_wire_field_type(v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T,
                                                std::unique_ptr<group_type>>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "group"});
              write_group_type(*v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T,
                                                std::unique_ptr<choice_type>>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "choice"});
              write_choice_type(*v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T, length_type>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "length"});
              write_length_type(v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T, discriminant_type>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "discriminant"});
              write_discriminant_type(v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T, save_position_type>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "save-position"});
              write_save_position_type(v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T, computed_field_type>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "computed-field"});
              write_computed_field_type(v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T,
                                                std::unique_ptr<repeat_type>>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "repeat"});
              write_repeat_type(*v, writer);
              writer.end_element();
            }
          },
          choice_item);
    }
  }

  inline choice_type
  read_choice_type(xb::xml_reader& reader) {
    choice_type result;
    result.name =
        xb::parse<std::string>(reader.attribute_value(xb::qname{"", "name"}));
    result.discriminant_field = xb::parse<std::string>(
        reader.attribute_value(xb::qname{"", "discriminant-field"}));
    auto start_depth = reader.depth();
    while (reader.read()) {
      if (reader.node_type() == xb::xml_node_type::end_element &&
          reader.depth() == start_depth)
        break;
      if (reader.node_type() != xb::xml_node_type::start_element) continue;
      auto& name = reader.name();
      if (name == xb::qname{"http://xb.dev/encoding", "alternative"}) {
        result.alternative.push_back(
            std::make_unique<alternative_type>(read_alternative_type(reader)));
      } else {
        xb::skip_element(reader);
      }
    }
    return result;
  }

  inline void
  write_choice_type(const choice_type& value, xb::xml_writer& writer) {
    writer.attribute(xb::qname{"", "name"}, xb::format(value.name));
    writer.attribute(xb::qname{"", "discriminant-field"},
                     xb::format(value.discriminant_field));
    for (const auto& item : value.alternative) {
      writer.start_element(xb::qname{"http://xb.dev/encoding", "alternative"});
      write_alternative_type(*item, writer);
      writer.end_element();
    }
  }

  inline alternative_type
  read_alternative_type(xb::xml_reader& reader) {
    alternative_type result;
    result.name =
        xb::parse<std::string>(reader.attribute_value(xb::qname{"", "name"}));
    result.discriminant_value = xb::parse<std::string>(
        reader.attribute_value(xb::qname{"", "discriminant-value"}));
    auto start_depth = reader.depth();
    while (reader.read()) {
      if (reader.node_type() == xb::xml_node_type::end_element &&
          reader.depth() == start_depth)
        break;
      if (reader.node_type() != xb::xml_node_type::start_element) continue;
      auto& name = reader.name();
      if (name == xb::qname{"http://xb.dev/encoding", "field"}) {
        result.choice.push_back(read_field_type(reader));
      } else if (name == xb::qname{"http://xb.dev/encoding", "padding"}) {
        result.choice.push_back(read_padding_field_type(reader));
      } else if (name == xb::qname{"http://xb.dev/encoding", "constant"}) {
        result.choice.push_back(read_constant_type(reader));
      } else if (name == xb::qname{"http://xb.dev/encoding", "wire-field"}) {
        result.choice.push_back(read_wire_field_type(reader));
      } else if (name == xb::qname{"http://xb.dev/encoding", "group"}) {
        result.choice.push_back(
            std::make_unique<group_type>(read_group_type(reader)));
      } else if (name == xb::qname{"http://xb.dev/encoding", "choice"}) {
        result.choice.push_back(
            std::make_unique<choice_type>(read_choice_type(reader)));
      } else if (name == xb::qname{"http://xb.dev/encoding", "length"}) {
        result.choice.push_back(read_length_type(reader));
      } else if (name == xb::qname{"http://xb.dev/encoding", "discriminant"}) {
        result.choice.push_back(read_discriminant_type(reader));
      } else if (name == xb::qname{"http://xb.dev/encoding", "save-position"}) {
        result.choice.push_back(read_save_position_type(reader));
      } else if (name ==
                 xb::qname{"http://xb.dev/encoding", "computed-field"}) {
        result.choice.push_back(read_computed_field_type(reader));
      } else if (name == xb::qname{"http://xb.dev/encoding", "repeat"}) {
        result.choice.push_back(
            std::make_unique<repeat_type>(read_repeat_type(reader)));
      } else {
        xb::skip_element(reader);
      }
    }
    return result;
  }

  inline void
  write_alternative_type(const alternative_type& value,
                         xb::xml_writer& writer) {
    writer.attribute(xb::qname{"", "name"}, xb::format(value.name));
    writer.attribute(xb::qname{"", "discriminant-value"},
                     xb::format(value.discriminant_value));
    for (const auto& choice_item : value.choice) {
      std::visit(
          [&](const auto& v) {
            using T = std::decay_t<decltype(v)>;
            if constexpr (std::is_same_v<T, field_type>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "field"});
              write_field_type(v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T, padding_field_type>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "padding"});
              write_padding_field_type(v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T, constant_type>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "constant"});
              write_constant_type(v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T, wire_field_type>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "wire-field"});
              write_wire_field_type(v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T,
                                                std::unique_ptr<group_type>>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "group"});
              write_group_type(*v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T,
                                                std::unique_ptr<choice_type>>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "choice"});
              write_choice_type(*v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T, length_type>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "length"});
              write_length_type(v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T, discriminant_type>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "discriminant"});
              write_discriminant_type(v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T, save_position_type>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "save-position"});
              write_save_position_type(v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T, computed_field_type>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "computed-field"});
              write_computed_field_type(v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T,
                                                std::unique_ptr<repeat_type>>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "repeat"});
              write_repeat_type(*v, writer);
              writer.end_element();
            }
          },
          choice_item);
    }
  }

  inline repeat_type
  read_repeat_type(xb::xml_reader& reader) {
    repeat_type result;
    {
      auto attr_val__ = reader.attribute_value(xb::qname{"", "count-field"});
      if (!attr_val__.empty()) {
        result.count_field = xb::parse<std::string>(attr_val__);
      }
    }
    {
      auto attr_val__ =
          reader.attribute_value(xb::qname{"", "element-size-field"});
      if (!attr_val__.empty()) {
        result.element_size_field = xb::parse<std::string>(attr_val__);
      }
    }
    {
      auto attr_val__ = reader.attribute_value(xb::qname{"", "fixed-size"});
      if (!attr_val__.empty()) {
        result.fixed_size = xb::parse<unsigned>(attr_val__);
      }
    }
    {
      auto attr_val__ = reader.attribute_value(xb::qname{"", "until"});
      if (!attr_val__.empty()) {
        result.until = repeat_until_type_from_string(attr_val__);
      }
    }
    {
      auto attr_val__ =
          reader.attribute_value(xb::qname{"", "until-delimiter"});
      if (!attr_val__.empty()) {
        result.until_delimiter = xb::parse<std::string>(attr_val__);
      }
    }
    auto start_depth = reader.depth();
    while (reader.read()) {
      if (reader.node_type() == xb::xml_node_type::end_element &&
          reader.depth() == start_depth)
        break;
      if (reader.node_type() != xb::xml_node_type::start_element) continue;
      auto& name = reader.name();
      if (name == xb::qname{"http://xb.dev/encoding", "field"}) {
        result.choice.push_back(read_field_type(reader));
      } else if (name == xb::qname{"http://xb.dev/encoding", "padding"}) {
        result.choice.push_back(read_padding_field_type(reader));
      } else if (name == xb::qname{"http://xb.dev/encoding", "length"}) {
        result.choice.push_back(read_length_type(reader));
      } else if (name == xb::qname{"http://xb.dev/encoding", "discriminant"}) {
        result.choice.push_back(read_discriminant_type(reader));
      } else if (name == xb::qname{"http://xb.dev/encoding", "delimiter"}) {
        result.choice.push_back(read_delimiter_type(reader));
      } else if (name == xb::qname{"http://xb.dev/encoding", "save-position"}) {
        result.choice.push_back(read_save_position_type(reader));
      } else if (name ==
                 xb::qname{"http://xb.dev/encoding", "computed-field"}) {
        result.choice.push_back(read_computed_field_type(reader));
      } else if (name == xb::qname{"http://xb.dev/encoding", "repeat"}) {
        result.choice.push_back(
            std::make_unique<repeat_type>(read_repeat_type(reader)));
      } else if (name == xb::qname{"http://xb.dev/encoding", "payload"}) {
        result.choice.push_back(read_payload_type(reader));
      } else {
        xb::skip_element(reader);
      }
    }
    return result;
  }

  inline void
  write_repeat_type(const repeat_type& value, xb::xml_writer& writer) {
    if (value.count_field) {
      writer.attribute(xb::qname{"", "count-field"},
                       xb::format(*value.count_field));
    }
    if (value.element_size_field) {
      writer.attribute(xb::qname{"", "element-size-field"},
                       xb::format(*value.element_size_field));
    }
    if (value.fixed_size) {
      writer.attribute(xb::qname{"", "fixed-size"},
                       xb::format(*value.fixed_size));
    }
    if (value.until) {
      writer.attribute(xb::qname{"", "until"},
                       std::string(to_string(*value.until)));
    }
    if (value.until_delimiter) {
      writer.attribute(xb::qname{"", "until-delimiter"},
                       xb::format(*value.until_delimiter));
    }
    for (const auto& choice_item : value.choice) {
      std::visit(
          [&](const auto& v) {
            using T = std::decay_t<decltype(v)>;
            if constexpr (std::is_same_v<T, field_type>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "field"});
              write_field_type(v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T, padding_field_type>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "padding"});
              write_padding_field_type(v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T, length_type>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "length"});
              write_length_type(v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T, discriminant_type>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "discriminant"});
              write_discriminant_type(v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T, delimiter_type>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "delimiter"});
              write_delimiter_type(v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T, save_position_type>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "save-position"});
              write_save_position_type(v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T, computed_field_type>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "computed-field"});
              write_computed_field_type(v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T,
                                                std::unique_ptr<repeat_type>>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "repeat"});
              write_repeat_type(*v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T, payload_type>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "payload"});
              write_payload_type(v, writer);
              writer.end_element();
            }
          },
          choice_item);
    }
  }

  inline import_type
  read_import_type(xb::xml_reader& reader) {
    import_type result;
    result.href =
        xb::parse<std::string>(reader.attribute_value(xb::qname{"", "href"}));
    return result;
  }

  inline void
  write_import_type(const import_type& value, xb::xml_writer& writer) {
    writer.attribute(xb::qname{"", "href"}, xb::format(value.href));
  }

  inline layer_type
  read_layer_type(xb::xml_reader& reader) {
    layer_type result;
    result.ref =
        xb::parse<std::string>(reader.attribute_value(xb::qname{"", "ref"}));
    {
      auto attr_val__ = reader.attribute_value(xb::qname{"", "match"});
      if (!attr_val__.empty()) {
        result.match = xb::parse<std::string>(attr_val__);
      }
    }
    {
      auto attr_val__ = reader.attribute_value(xb::qname{"", "value"});
      if (!attr_val__.empty()) {
        result.value = xb::parse<std::string>(attr_val__);
      }
    }
    return result;
  }

  inline void
  write_layer_type(const layer_type& value, xb::xml_writer& writer) {
    writer.attribute(xb::qname{"", "ref"}, xb::format(value.ref));
    if (value.match) {
      writer.attribute(xb::qname{"", "match"}, xb::format(*value.match));
    }
    if (value.value) {
      writer.attribute(xb::qname{"", "value"}, xb::format(*value.value));
    }
  }

  inline selector_type
  read_selector_type(xb::xml_reader& reader) {
    selector_type result;
    {
      auto attr_val__ = reader.attribute_value(xb::qname{"", "qname"});
      if (!attr_val__.empty()) {
        result.qname = xb::parse<std::string>(attr_val__);
      }
    }
    {
      auto attr_val__ = reader.attribute_value(xb::qname{"", "path"});
      if (!attr_val__.empty()) {
        result.path = xb::parse<std::string>(attr_val__);
      }
    }
    {
      auto attr_val__ = reader.attribute_value(xb::qname{"", "type"});
      if (!attr_val__.empty()) {
        result.type = xb::parse<std::string>(attr_val__);
      }
    }
    {
      auto attr_val__ = reader.attribute_value(xb::qname{"", "namespace"});
      if (!attr_val__.empty()) {
        result.namespace_ = xb::parse<std::string>(attr_val__);
      }
    }
    {
      auto attr_val__ = reader.attribute_value(xb::qname{"", "attribute"});
      if (!attr_val__.empty()) {
        result.attribute = xb::parse<std::string>(attr_val__);
      }
    }
    return result;
  }

  inline void
  write_selector_type(const selector_type& value, xb::xml_writer& writer) {
    if (value.qname) {
      writer.attribute(xb::qname{"", "qname"}, xb::format(*value.qname));
    }
    if (value.path) {
      writer.attribute(xb::qname{"", "path"}, xb::format(*value.path));
    }
    if (value.type) {
      writer.attribute(xb::qname{"", "type"}, xb::format(*value.type));
    }
    if (value.namespace_) {
      writer.attribute(xb::qname{"", "namespace"},
                       xb::format(*value.namespace_));
    }
    if (value.attribute) {
      writer.attribute(xb::qname{"", "attribute"},
                       xb::format(*value.attribute));
    }
  }

  inline padding_field_type
  read_padding_field_type(xb::xml_reader& reader) {
    padding_field_type result;
    {
      auto attr_val__ = reader.attribute_value(xb::qname{"", "bits"});
      if (!attr_val__.empty()) {
        result.bits = xb::parse<unsigned>(attr_val__);
      }
    }
    {
      auto attr_val__ = reader.attribute_value(xb::qname{"", "align-to"});
      if (!attr_val__.empty()) {
        result.align_to = xb::parse<unsigned>(attr_val__);
      }
    }
    {
      auto attr_val__ = reader.attribute_value(xb::qname{"", "fill"});
      if (!attr_val__.empty()) {
        result.fill = xb::parse<std::string>(attr_val__);
      }
    }
    return result;
  }

  inline void
  write_padding_field_type(const padding_field_type& value,
                           xb::xml_writer& writer) {
    if (value.bits) {
      writer.attribute(xb::qname{"", "bits"}, xb::format(*value.bits));
    }
    if (value.align_to) {
      writer.attribute(xb::qname{"", "align-to"}, xb::format(*value.align_to));
    }
    if (value.fill) {
      writer.attribute(xb::qname{"", "fill"}, xb::format(*value.fill));
    }
  }

  inline constant_type
  read_constant_type(xb::xml_reader& reader) {
    constant_type result;
    result.name =
        xb::parse<std::string>(reader.attribute_value(xb::qname{"", "name"}));
    {
      auto attr_val__ = reader.attribute_value(xb::qname{"", "type"});
      if (!attr_val__.empty()) {
        result.type = xb::parse<std::string>(attr_val__);
      }
    }
    result.value =
        xb::parse<std::string>(reader.attribute_value(xb::qname{"", "value"}));
    return result;
  }

  inline void
  write_constant_type(const constant_type& value, xb::xml_writer& writer) {
    writer.attribute(xb::qname{"", "name"}, xb::format(value.name));
    if (value.type) {
      writer.attribute(xb::qname{"", "type"}, xb::format(*value.type));
    }
    writer.attribute(xb::qname{"", "value"}, xb::format(value.value));
  }

  inline discriminant_type
  read_discriminant_type(xb::xml_reader& reader) {
    discriminant_type result;
    result.field =
        xb::parse<std::string>(reader.attribute_value(xb::qname{"", "field"}));
    return result;
  }

  inline void
  write_discriminant_type(const discriminant_type& value,
                          xb::xml_writer& writer) {
    writer.attribute(xb::qname{"", "field"}, xb::format(value.field));
  }

  inline save_position_type
  read_save_position_type(xb::xml_reader& reader) {
    save_position_type result;
    result.name =
        xb::parse<std::string>(reader.attribute_value(xb::qname{"", "name"}));
    return result;
  }

  inline void
  write_save_position_type(const save_position_type& value,
                           xb::xml_writer& writer) {
    writer.attribute(xb::qname{"", "name"}, xb::format(value.name));
  }

  inline payload_type
  read_payload_type(xb::xml_reader& reader) {
    payload_type result;
    {
      auto attr_val__ = reader.attribute_value(xb::qname{"", "length-field"});
      if (!attr_val__.empty()) {
        result.length_field = xb::parse<std::string>(attr_val__);
      }
    }
    return result;
  }

  inline void
  write_payload_type(const payload_type& value, xb::xml_writer& writer) {
    if (value.length_field) {
      writer.attribute(xb::qname{"", "length-field"},
                       xb::format(*value.length_field));
    }
  }

  inline present_when_type
  read_present_when_type(xb::xml_reader& reader) {
    present_when_type result;
    {
      auto attr_val__ = reader.attribute_value(xb::qname{"", "expr"});
      if (!attr_val__.empty()) {
        result.expr = xb::parse<std::string>(attr_val__);
      }
    }
    {
      auto attr_val__ = reader.attribute_value(xb::qname{"", "field"});
      if (!attr_val__.empty()) {
        result.field = xb::parse<std::string>(attr_val__);
      }
    }
    {
      auto attr_val__ = reader.attribute_value(xb::qname{"", "field-equals"});
      if (!attr_val__.empty()) {
        result.field_equals = xb::parse<std::string>(attr_val__);
      }
    }
    return result;
  }

  inline void
  write_present_when_type(const present_when_type& value,
                          xb::xml_writer& writer) {
    if (value.expr) {
      writer.attribute(xb::qname{"", "expr"}, xb::format(*value.expr));
    }
    if (value.field) {
      writer.attribute(xb::qname{"", "field"}, xb::format(*value.field));
    }
    if (value.field_equals) {
      writer.attribute(xb::qname{"", "field-equals"},
                       xb::format(*value.field_equals));
    }
  }

  inline transform_type
  read_transform_type(xb::xml_reader& reader) {
    transform_type result;
    result.encode =
        xb::parse<std::string>(reader.attribute_value(xb::qname{"", "encode"}));
    result.decode =
        xb::parse<std::string>(reader.attribute_value(xb::qname{"", "decode"}));
    {
      auto attr_val__ = reader.attribute_value(xb::qname{"", "header"});
      if (!attr_val__.empty()) {
        result.header = xb::parse<std::string>(attr_val__);
      }
    }
    return result;
  }

  inline void
  write_transform_type(const transform_type& value, xb::xml_writer& writer) {
    writer.attribute(xb::qname{"", "encode"}, xb::format(value.encode));
    writer.attribute(xb::qname{"", "decode"}, xb::format(value.decode));
    if (value.header) {
      writer.attribute(xb::qname{"", "header"}, xb::format(*value.header));
    }
  }

  inline enum_entry_type
  read_enum_entry_type(xb::xml_reader& reader) {
    enum_entry_type result;
    result.xsd_value = xb::parse<std::string>(
        reader.attribute_value(xb::qname{"", "xsd-value"}));
    result.wire_value = xb::parse<std::string>(
        reader.attribute_value(xb::qname{"", "wire-value"}));
    return result;
  }

  inline void
  write_enum_entry_type(const enum_entry_type& value, xb::xml_writer& writer) {
    writer.attribute(xb::qname{"", "xsd-value"}, xb::format(value.xsd_value));
    writer.attribute(xb::qname{"", "wire-value"}, xb::format(value.wire_value));
  }

  inline delimiter_type
  read_delimiter_type(xb::xml_reader& reader) {
    delimiter_type result;
    result.value =
        xb::parse<std::string>(reader.attribute_value(xb::qname{"", "value"}));
    {
      auto attr_val__ = reader.attribute_value(xb::qname{"", "escape"});
      if (!attr_val__.empty()) {
        result.escape = xb::parse<std::string>(attr_val__);
      }
    }
    {
      auto attr_val__ = reader.attribute_value(xb::qname{"", "escape-xor"});
      if (!attr_val__.empty()) {
        result.escape_xor = xb::parse<std::string>(attr_val__);
      }
    }
    return result;
  }

  inline void
  write_delimiter_type(const delimiter_type& value, xb::xml_writer& writer) {
    writer.attribute(xb::qname{"", "value"}, xb::format(value.value));
    if (value.escape) {
      writer.attribute(xb::qname{"", "escape"}, xb::format(*value.escape));
    }
    if (value.escape_xor) {
      writer.attribute(xb::qname{"", "escape-xor"},
                       xb::format(*value.escape_xor));
    }
  }

  inline computed_field_type
  read_computed_field_type(xb::xml_reader& reader) {
    computed_field_type result;
    result.name =
        xb::parse<std::string>(reader.attribute_value(xb::qname{"", "name"}));
    result.bits =
        xb::parse<unsigned>(reader.attribute_value(xb::qname{"", "bits"}));
    result.algorithm = xb::parse<std::string>(
        reader.attribute_value(xb::qname{"", "algorithm"}));
    result.over =
        xb::parse<std::string>(reader.attribute_value(xb::qname{"", "over"}));
    {
      auto attr_val__ = reader.attribute_value(xb::qname{"", "byte-order"});
      if (!attr_val__.empty()) {
        result.byte_order = byte_order_type_from_string(attr_val__);
      }
    }
    {
      auto attr_val__ = reader.attribute_value(xb::qname{"", "seed"});
      if (!attr_val__.empty()) {
        result.seed = xb::parse<std::string>(attr_val__);
      }
    }
    {
      auto attr_val__ = reader.attribute_value(xb::qname{"", "seed-expr"});
      if (!attr_val__.empty()) {
        result.seed_expr = xb::parse<std::string>(attr_val__);
      }
    }
    return result;
  }

  inline void
  write_computed_field_type(const computed_field_type& value,
                            xb::xml_writer& writer) {
    writer.attribute(xb::qname{"", "name"}, xb::format(value.name));
    writer.attribute(xb::qname{"", "bits"}, xb::format(value.bits));
    writer.attribute(xb::qname{"", "algorithm"}, xb::format(value.algorithm));
    writer.attribute(xb::qname{"", "over"}, xb::format(value.over));
    if (value.byte_order) {
      writer.attribute(xb::qname{"", "byte-order"},
                       std::string(to_string(*value.byte_order)));
    }
    if (value.seed) {
      writer.attribute(xb::qname{"", "seed"}, xb::format(*value.seed));
    }
    if (value.seed_expr) {
      writer.attribute(xb::qname{"", "seed-expr"},
                       xb::format(*value.seed_expr));
    }
  }

  inline wire_field_type
  read_wire_field_type(xb::xml_reader& reader) {
    wire_field_type result;
    result.name =
        xb::parse<std::string>(reader.attribute_value(xb::qname{"", "name"}));
    result.bits =
        xb::parse<unsigned>(reader.attribute_value(xb::qname{"", "bits"}));
    {
      auto attr_val__ = reader.attribute_value(xb::qname{"", "encoding"});
      if (!attr_val__.empty()) {
        result.encoding = primitive_encoding_type_from_string(attr_val__);
      }
    }
    {
      auto attr_val__ = reader.attribute_value(xb::qname{"", "byte-order"});
      if (!attr_val__.empty()) {
        result.byte_order = byte_order_type_from_string(attr_val__);
      }
    }
    {
      auto attr_val__ = reader.attribute_value(xb::qname{"", "value"});
      if (!attr_val__.empty()) {
        result.value = xb::parse<std::string>(attr_val__);
      }
    }
    return result;
  }

  inline void
  write_wire_field_type(const wire_field_type& value, xb::xml_writer& writer) {
    writer.attribute(xb::qname{"", "name"}, xb::format(value.name));
    writer.attribute(xb::qname{"", "bits"}, xb::format(value.bits));
    if (value.encoding) {
      writer.attribute(xb::qname{"", "encoding"},
                       std::string(to_string(*value.encoding)));
    }
    if (value.byte_order) {
      writer.attribute(xb::qname{"", "byte-order"},
                       std::string(to_string(*value.byte_order)));
    }
    if (value.value) {
      writer.attribute(xb::qname{"", "value"}, xb::format(*value.value));
    }
  }

  inline defaults_type
  read_defaults_type(xb::xml_reader& reader) {
    defaults_type result;
    {
      auto attr_val__ = reader.attribute_value(xb::qname{"", "byte-order"});
      if (!attr_val__.empty()) {
        result.byte_order = byte_order_type_from_string(attr_val__);
      }
    }
    {
      auto attr_val__ = reader.attribute_value(xb::qname{"", "bit-order"});
      if (!attr_val__.empty()) {
        result.bit_order = bit_order_type_from_string(attr_val__);
      }
    }
    {
      auto attr_val__ = reader.attribute_value(xb::qname{"", "alignment"});
      if (!attr_val__.empty()) {
        result.alignment = xb::parse<unsigned>(attr_val__);
      }
    }
    {
      auto attr_val__ = reader.attribute_value(xb::qname{"", "string-padding"});
      if (!attr_val__.empty()) {
        result.string_padding = padding_type_from_string(attr_val__);
      }
    }
    {
      auto attr_val__ =
          reader.attribute_value(xb::qname{"", "string-encoding"});
      if (!attr_val__.empty()) {
        result.string_encoding = charset_type_from_string(attr_val__);
      }
    }
    return result;
  }

  inline void
  write_defaults_type(const defaults_type& value, xb::xml_writer& writer) {
    if (value.byte_order) {
      writer.attribute(xb::qname{"", "byte-order"},
                       std::string(to_string(*value.byte_order)));
    }
    if (value.bit_order) {
      writer.attribute(xb::qname{"", "bit-order"},
                       std::string(to_string(*value.bit_order)));
    }
    if (value.alignment) {
      writer.attribute(xb::qname{"", "alignment"},
                       xb::format(*value.alignment));
    }
    if (value.string_padding) {
      writer.attribute(xb::qname{"", "string-padding"},
                       std::string(to_string(*value.string_padding)));
    }
    if (value.string_encoding) {
      writer.attribute(xb::qname{"", "string-encoding"},
                       std::string(to_string(*value.string_encoding)));
    }
  }

  inline string_encoding_type
  read_string_encoding_type(xb::xml_reader& reader) {
    string_encoding_type result;
    {
      auto attr_val__ = reader.attribute_value(xb::qname{"", "charset"});
      if (!attr_val__.empty()) {
        result.charset = charset_type_from_string(attr_val__);
      }
    }
    {
      auto attr_val__ = reader.attribute_value(xb::qname{"", "padding"});
      if (!attr_val__.empty()) {
        result.padding = padding_type_from_string(attr_val__);
      }
    }
    {
      auto attr_val__ = reader.attribute_value(xb::qname{"", "terminator"});
      if (!attr_val__.empty()) {
        result.terminator = xb::parse<std::string>(attr_val__);
      }
    }
    {
      auto attr_val__ = reader.attribute_value(xb::qname{"", "length-field"});
      if (!attr_val__.empty()) {
        result.length_field = xb::parse<std::string>(attr_val__);
      }
    }
    return result;
  }

  inline void
  write_string_encoding_type(const string_encoding_type& value,
                             xb::xml_writer& writer) {
    if (value.charset) {
      writer.attribute(xb::qname{"", "charset"},
                       std::string(to_string(*value.charset)));
    }
    if (value.padding) {
      writer.attribute(xb::qname{"", "padding"},
                       std::string(to_string(*value.padding)));
    }
    if (value.terminator) {
      writer.attribute(xb::qname{"", "terminator"},
                       xb::format(*value.terminator));
    }
    if (value.length_field) {
      writer.attribute(xb::qname{"", "length-field"},
                       xb::format(*value.length_field));
    }
  }

  inline length_type
  read_length_type(xb::xml_reader& reader) {
    length_type result;
    result.field =
        xb::parse<std::string>(reader.attribute_value(xb::qname{"", "field"}));
    {
      auto attr_val__ = reader.attribute_value(xb::qname{"", "includes"});
      if (!attr_val__.empty()) {
        result.includes = length_includes_type_from_string(attr_val__);
      }
    }
    {
      auto attr_val__ = reader.attribute_value(xb::qname{"", "unit"});
      if (!attr_val__.empty()) {
        result.unit = length_unit_type_from_string(attr_val__);
      }
    }
    {
      auto attr_val__ = reader.attribute_value(xb::qname{"", "adjust"});
      if (!attr_val__.empty()) { result.adjust = xb::parse<int>(attr_val__); }
    }
    return result;
  }

  inline void
  write_length_type(const length_type& value, xb::xml_writer& writer) {
    writer.attribute(xb::qname{"", "field"}, xb::format(value.field));
    if (value.includes) {
      writer.attribute(xb::qname{"", "includes"},
                       std::string(to_string(*value.includes)));
    }
    if (value.unit) {
      writer.attribute(xb::qname{"", "unit"},
                       std::string(to_string(*value.unit)));
    }
    if (value.adjust) {
      writer.attribute(xb::qname{"", "adjust"}, xb::format(*value.adjust));
    }
  }

  inline frame_stack_type
  read_frame_stack_type(xb::xml_reader& reader) {
    frame_stack_type result;
    result.name =
        xb::parse<std::string>(reader.attribute_value(xb::qname{"", "name"}));
    auto start_depth = reader.depth();
    while (reader.read()) {
      if (reader.node_type() == xb::xml_node_type::end_element &&
          reader.depth() == start_depth)
        break;
      if (reader.node_type() != xb::xml_node_type::start_element) continue;
      auto& name = reader.name();
      if (name == xb::qname{"http://xb.dev/encoding", "layer"}) {
        result.layer.push_back(read_layer_type(reader));
      } else {
        xb::skip_element(reader);
      }
    }
    return result;
  }

  inline void
  write_frame_stack_type(const frame_stack_type& value,
                         xb::xml_writer& writer) {
    writer.attribute(xb::qname{"", "name"}, xb::format(value.name));
    for (const auto& item : value.layer) {
      writer.start_element(xb::qname{"http://xb.dev/encoding", "layer"});
      write_layer_type(item, writer);
      writer.end_element();
    }
  }

  inline enum_map_type
  read_enum_map_type(xb::xml_reader& reader) {
    enum_map_type result;
    {
      auto attr_val__ = reader.attribute_value(xb::qname{"", "encode-by"});
      if (!attr_val__.empty()) {
        result.encode_by = enum_encode_by_type_from_string(attr_val__);
      }
    }
    auto start_depth = reader.depth();
    while (reader.read()) {
      if (reader.node_type() == xb::xml_node_type::end_element &&
          reader.depth() == start_depth)
        break;
      if (reader.node_type() != xb::xml_node_type::start_element) continue;
      auto& name = reader.name();
      if (name == xb::qname{"http://xb.dev/encoding", "entry"}) {
        result.entry.push_back(read_enum_entry_type(reader));
      } else {
        xb::skip_element(reader);
      }
    }
    return result;
  }

  inline void
  write_enum_map_type(const enum_map_type& value, xb::xml_writer& writer) {
    if (value.encode_by) {
      writer.attribute(xb::qname{"", "encode-by"},
                       std::string(to_string(*value.encode_by)));
    }
    for (const auto& item : value.entry) {
      writer.start_element(xb::qname{"http://xb.dev/encoding", "entry"});
      write_enum_entry_type(item, writer);
      writer.end_element();
    }
  }

  inline dimension_type
  read_dimension_type(xb::xml_reader& reader) {
    dimension_type result;
    result.count_field = xb::parse<std::string>(
        reader.attribute_value(xb::qname{"", "count-field"}));
    {
      auto attr_val__ =
          reader.attribute_value(xb::qname{"", "block-length-field"});
      if (!attr_val__.empty()) {
        result.block_length_field = xb::parse<std::string>(attr_val__);
      }
    }
    auto start_depth = reader.depth();
    while (reader.read()) {
      if (reader.node_type() == xb::xml_node_type::end_element &&
          reader.depth() == start_depth)
        break;
      if (reader.node_type() != xb::xml_node_type::start_element) continue;
      auto& name = reader.name();
      if (name == xb::qname{"http://xb.dev/encoding", "wire-field"}) {
        result.wire_field.push_back(read_wire_field_type(reader));
      } else {
        xb::skip_element(reader);
      }
    }
    return result;
  }

  inline void
  write_dimension_type(const dimension_type& value, xb::xml_writer& writer) {
    writer.attribute(xb::qname{"", "count-field"},
                     xb::format(value.count_field));
    if (value.block_length_field) {
      writer.attribute(xb::qname{"", "block-length-field"},
                       xb::format(*value.block_length_field));
    }
    for (const auto& item : value.wire_field) {
      writer.start_element(xb::qname{"http://xb.dev/encoding", "wire-field"});
      write_wire_field_type(item, writer);
      writer.end_element();
    }
  }

  inline field_type
  read_field_type(xb::xml_reader& reader) {
    field_type result;
    result.name =
        xb::parse<std::string>(reader.attribute_value(xb::qname{"", "name"}));
    result.bits =
        xb::parse<unsigned>(reader.attribute_value(xb::qname{"", "bits"}));
    {
      auto attr_val__ = reader.attribute_value(xb::qname{"", "type"});
      if (!attr_val__.empty()) {
        result.type = xb::parse<std::string>(attr_val__);
      }
    }
    {
      auto attr_val__ = reader.attribute_value(xb::qname{"", "encoding"});
      if (!attr_val__.empty()) {
        result.encoding = primitive_encoding_type_from_string(attr_val__);
      }
    }
    {
      auto attr_val__ = reader.attribute_value(xb::qname{"", "byte-order"});
      if (!attr_val__.empty()) {
        result.byte_order = byte_order_type_from_string(attr_val__);
      }
    }
    {
      auto attr_val__ = reader.attribute_value(xb::qname{"", "offset"});
      if (!attr_val__.empty()) {
        result.offset = xb::parse<unsigned>(attr_val__);
      }
    }
    {
      auto attr_val__ = reader.attribute_value(xb::qname{"", "null-value"});
      if (!attr_val__.empty()) {
        result.null_value = xb::parse<std::string>(attr_val__);
      }
    }
    {
      auto attr_val__ = reader.attribute_value(xb::qname{"", "size"});
      if (!attr_val__.empty()) {
        result.size = xb::parse<std::string>(attr_val__);
      }
    }
    auto start_depth = reader.depth();
    while (reader.read()) {
      if (reader.node_type() == xb::xml_node_type::end_element &&
          reader.depth() == start_depth)
        break;
      if (reader.node_type() != xb::xml_node_type::start_element) continue;
      auto& name = reader.name();
      if (name == xb::qname{"http://xb.dev/encoding", "present-when"}) {
        result.present_when = read_present_when_type(reader);
      } else if (name ==
                 xb::qname{"http://xb.dev/encoding", "string-encoding"}) {
        result.string_encoding = read_string_encoding_type(reader);
      } else if (name == xb::qname{"http://xb.dev/encoding", "transform"}) {
        result.transform = read_transform_type(reader);
      } else if (name == xb::qname{"http://xb.dev/encoding", "enum-map"}) {
        result.enum_map = read_enum_map_type(reader);
      } else {
        xb::skip_element(reader);
      }
    }
    return result;
  }

  inline void
  write_field_type(const field_type& value, xb::xml_writer& writer) {
    writer.attribute(xb::qname{"", "name"}, xb::format(value.name));
    writer.attribute(xb::qname{"", "bits"}, xb::format(value.bits));
    if (value.type) {
      writer.attribute(xb::qname{"", "type"}, xb::format(*value.type));
    }
    if (value.encoding) {
      writer.attribute(xb::qname{"", "encoding"},
                       std::string(to_string(*value.encoding)));
    }
    if (value.byte_order) {
      writer.attribute(xb::qname{"", "byte-order"},
                       std::string(to_string(*value.byte_order)));
    }
    if (value.offset) {
      writer.attribute(xb::qname{"", "offset"}, xb::format(*value.offset));
    }
    if (value.null_value) {
      writer.attribute(xb::qname{"", "null-value"},
                       xb::format(*value.null_value));
    }
    if (value.size) {
      writer.attribute(xb::qname{"", "size"}, xb::format(*value.size));
    }
    if (value.present_when) {
      writer.start_element(xb::qname{"http://xb.dev/encoding", "present-when"});
      write_present_when_type(*value.present_when, writer);
      writer.end_element();
    }
    if (value.string_encoding) {
      writer.start_element(
          xb::qname{"http://xb.dev/encoding", "string-encoding"});
      write_string_encoding_type(*value.string_encoding, writer);
      writer.end_element();
    }
    if (value.transform) {
      writer.start_element(xb::qname{"http://xb.dev/encoding", "transform"});
      write_transform_type(*value.transform, writer);
      writer.end_element();
    }
    if (value.enum_map) {
      writer.start_element(xb::qname{"http://xb.dev/encoding", "enum-map"});
      write_enum_map_type(*value.enum_map, writer);
      writer.end_element();
    }
  }

  inline framing_type
  read_framing_type(xb::xml_reader& reader) {
    framing_type result;
    result.name =
        xb::parse<std::string>(reader.attribute_value(xb::qname{"", "name"}));
    {
      auto attr_val__ = reader.attribute_value(xb::qname{"", "byte-order"});
      if (!attr_val__.empty()) {
        result.byte_order = byte_order_type_from_string(attr_val__);
      }
    }
    {
      auto attr_val__ = reader.attribute_value(xb::qname{"", "bit-order"});
      if (!attr_val__.empty()) {
        result.bit_order = bit_order_type_from_string(attr_val__);
      }
    }
    auto start_depth = reader.depth();
    while (reader.read()) {
      if (reader.node_type() == xb::xml_node_type::end_element &&
          reader.depth() == start_depth)
        break;
      if (reader.node_type() != xb::xml_node_type::start_element) continue;
      auto& name = reader.name();
      if (name == xb::qname{"http://xb.dev/encoding", "field"}) {
        result.choice.push_back(read_field_type(reader));
      } else if (name == xb::qname{"http://xb.dev/encoding", "padding"}) {
        result.choice.push_back(read_padding_field_type(reader));
      } else if (name == xb::qname{"http://xb.dev/encoding", "length"}) {
        result.choice.push_back(read_length_type(reader));
      } else if (name == xb::qname{"http://xb.dev/encoding", "discriminant"}) {
        result.choice.push_back(read_discriminant_type(reader));
      } else if (name == xb::qname{"http://xb.dev/encoding", "delimiter"}) {
        result.choice.push_back(read_delimiter_type(reader));
      } else if (name == xb::qname{"http://xb.dev/encoding", "save-position"}) {
        result.choice.push_back(read_save_position_type(reader));
      } else if (name ==
                 xb::qname{"http://xb.dev/encoding", "computed-field"}) {
        result.choice.push_back(read_computed_field_type(reader));
      } else if (name == xb::qname{"http://xb.dev/encoding", "repeat"}) {
        result.choice.push_back(
            std::make_unique<repeat_type>(read_repeat_type(reader)));
      } else if (name == xb::qname{"http://xb.dev/encoding", "payload"}) {
        result.choice.push_back(read_payload_type(reader));
      } else {
        xb::skip_element(reader);
      }
    }
    return result;
  }

  inline void
  write_framing_type(const framing_type& value, xb::xml_writer& writer) {
    writer.attribute(xb::qname{"", "name"}, xb::format(value.name));
    if (value.byte_order) {
      writer.attribute(xb::qname{"", "byte-order"},
                       std::string(to_string(*value.byte_order)));
    }
    if (value.bit_order) {
      writer.attribute(xb::qname{"", "bit-order"},
                       std::string(to_string(*value.bit_order)));
    }
    for (const auto& choice_item : value.choice) {
      std::visit(
          [&](const auto& v) {
            using T = std::decay_t<decltype(v)>;
            if constexpr (std::is_same_v<T, field_type>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "field"});
              write_field_type(v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T, padding_field_type>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "padding"});
              write_padding_field_type(v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T, length_type>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "length"});
              write_length_type(v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T, discriminant_type>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "discriminant"});
              write_discriminant_type(v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T, delimiter_type>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "delimiter"});
              write_delimiter_type(v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T, save_position_type>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "save-position"});
              write_save_position_type(v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T, computed_field_type>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "computed-field"});
              write_computed_field_type(v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T,
                                                std::unique_ptr<repeat_type>>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "repeat"});
              write_repeat_type(*v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T, payload_type>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "payload"});
              write_payload_type(v, writer);
              writer.end_element();
            }
          },
          choice_item);
    }
  }

  inline extensions_type
  read_extensions_type(xb::xml_reader& reader) {
    extensions_type result;
    auto start_depth = reader.depth();
    while (reader.read()) {
      if (reader.node_type() == xb::xml_node_type::end_element &&
          reader.depth() == start_depth)
        break;
      if (reader.node_type() != xb::xml_node_type::start_element) continue;
      auto& name = reader.name();
      if (name == xb::qname{"http://xb.dev/encoding", "field"}) {
        result.choice.push_back(read_field_type(reader));
      } else if (name == xb::qname{"http://xb.dev/encoding", "padding"}) {
        result.choice.push_back(read_padding_field_type(reader));
      } else if (name == xb::qname{"http://xb.dev/encoding", "constant"}) {
        result.choice.push_back(read_constant_type(reader));
      } else if (name == xb::qname{"http://xb.dev/encoding", "wire-field"}) {
        result.choice.push_back(read_wire_field_type(reader));
      } else if (name == xb::qname{"http://xb.dev/encoding", "group"}) {
        result.choice.push_back(
            std::make_unique<group_type>(read_group_type(reader)));
      } else if (name == xb::qname{"http://xb.dev/encoding", "choice"}) {
        result.choice.push_back(
            std::make_unique<choice_type>(read_choice_type(reader)));
      } else if (name == xb::qname{"http://xb.dev/encoding", "length"}) {
        result.choice.push_back(read_length_type(reader));
      } else if (name == xb::qname{"http://xb.dev/encoding", "discriminant"}) {
        result.choice.push_back(read_discriminant_type(reader));
      } else if (name == xb::qname{"http://xb.dev/encoding", "save-position"}) {
        result.choice.push_back(read_save_position_type(reader));
      } else if (name ==
                 xb::qname{"http://xb.dev/encoding", "computed-field"}) {
        result.choice.push_back(read_computed_field_type(reader));
      } else if (name == xb::qname{"http://xb.dev/encoding", "repeat"}) {
        result.choice.push_back(
            std::make_unique<repeat_type>(read_repeat_type(reader)));
      } else {
        xb::skip_element(reader);
      }
    }
    return result;
  }

  inline void
  write_extensions_type(const extensions_type& value, xb::xml_writer& writer) {
    for (const auto& choice_item : value.choice) {
      std::visit(
          [&](const auto& v) {
            using T = std::decay_t<decltype(v)>;
            if constexpr (std::is_same_v<T, field_type>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "field"});
              write_field_type(v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T, padding_field_type>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "padding"});
              write_padding_field_type(v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T, constant_type>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "constant"});
              write_constant_type(v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T, wire_field_type>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "wire-field"});
              write_wire_field_type(v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T,
                                                std::unique_ptr<group_type>>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "group"});
              write_group_type(*v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T,
                                                std::unique_ptr<choice_type>>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "choice"});
              write_choice_type(*v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T, length_type>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "length"});
              write_length_type(v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T, discriminant_type>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "discriminant"});
              write_discriminant_type(v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T, save_position_type>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "save-position"});
              write_save_position_type(v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T, computed_field_type>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "computed-field"});
              write_computed_field_type(v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T,
                                                std::unique_ptr<repeat_type>>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "repeat"});
              write_repeat_type(*v, writer);
              writer.end_element();
            }
          },
          choice_item);
    }
  }

  inline message_type
  read_message_type(xb::xml_reader& reader) {
    message_type result;
    result.name =
        xb::parse<std::string>(reader.attribute_value(xb::qname{"", "name"}));
    {
      auto attr_val__ = reader.attribute_value(xb::qname{"", "type"});
      if (!attr_val__.empty()) {
        result.type = xb::parse<std::string>(attr_val__);
      }
    }
    {
      auto attr_val__ =
          reader.attribute_value(xb::qname{"", "discriminant-value"});
      if (!attr_val__.empty()) {
        result.discriminant_value = xb::parse<std::string>(attr_val__);
      }
    }
    {
      auto attr_val__ = reader.attribute_value(xb::qname{"", "framing"});
      if (!attr_val__.empty()) {
        result.framing = xb::parse<std::string>(attr_val__);
      }
    }
    {
      auto attr_val__ = reader.attribute_value(xb::qname{"", "frame-stack"});
      if (!attr_val__.empty()) {
        result.frame_stack = xb::parse<std::string>(attr_val__);
      }
    }
    {
      auto attr_val__ = reader.attribute_value(xb::qname{"", "byte-order"});
      if (!attr_val__.empty()) {
        result.byte_order = byte_order_type_from_string(attr_val__);
      }
    }
    {
      auto attr_val__ = reader.attribute_value(xb::qname{"", "bit-order"});
      if (!attr_val__.empty()) {
        result.bit_order = bit_order_type_from_string(attr_val__);
      }
    }
    auto start_depth = reader.depth();
    while (reader.read()) {
      if (reader.node_type() == xb::xml_node_type::end_element &&
          reader.depth() == start_depth)
        break;
      if (reader.node_type() != xb::xml_node_type::start_element) continue;
      auto& name = reader.name();
      if (name == xb::qname{"http://xb.dev/encoding", "selector"}) {
        result.selector = read_selector_type(reader);
      } else if (name == xb::qname{"http://xb.dev/encoding", "field"}) {
        result.choice.push_back(read_field_type(reader));
      } else if (name == xb::qname{"http://xb.dev/encoding", "padding"}) {
        result.choice.push_back(read_padding_field_type(reader));
      } else if (name == xb::qname{"http://xb.dev/encoding", "constant"}) {
        result.choice.push_back(read_constant_type(reader));
      } else if (name == xb::qname{"http://xb.dev/encoding", "wire-field"}) {
        result.choice.push_back(read_wire_field_type(reader));
      } else if (name == xb::qname{"http://xb.dev/encoding", "group"}) {
        result.choice.push_back(
            std::make_unique<group_type>(read_group_type(reader)));
      } else if (name == xb::qname{"http://xb.dev/encoding", "choice"}) {
        result.choice.push_back(
            std::make_unique<choice_type>(read_choice_type(reader)));
      } else if (name == xb::qname{"http://xb.dev/encoding", "length"}) {
        result.choice.push_back(read_length_type(reader));
      } else if (name == xb::qname{"http://xb.dev/encoding", "discriminant"}) {
        result.choice.push_back(read_discriminant_type(reader));
      } else if (name == xb::qname{"http://xb.dev/encoding", "save-position"}) {
        result.choice.push_back(read_save_position_type(reader));
      } else if (name ==
                 xb::qname{"http://xb.dev/encoding", "computed-field"}) {
        result.choice.push_back(read_computed_field_type(reader));
      } else if (name == xb::qname{"http://xb.dev/encoding", "repeat"}) {
        result.choice.push_back(
            std::make_unique<repeat_type>(read_repeat_type(reader)));
      } else if (name == xb::qname{"http://xb.dev/encoding", "extensions"}) {
        result.extensions = read_extensions_type(reader);
      } else {
        xb::skip_element(reader);
      }
    }
    return result;
  }

  inline void
  write_message_type(const message_type& value, xb::xml_writer& writer) {
    writer.attribute(xb::qname{"", "name"}, xb::format(value.name));
    if (value.type) {
      writer.attribute(xb::qname{"", "type"}, xb::format(*value.type));
    }
    if (value.discriminant_value) {
      writer.attribute(xb::qname{"", "discriminant-value"},
                       xb::format(*value.discriminant_value));
    }
    if (value.framing) {
      writer.attribute(xb::qname{"", "framing"}, xb::format(*value.framing));
    }
    if (value.frame_stack) {
      writer.attribute(xb::qname{"", "frame-stack"},
                       xb::format(*value.frame_stack));
    }
    if (value.byte_order) {
      writer.attribute(xb::qname{"", "byte-order"},
                       std::string(to_string(*value.byte_order)));
    }
    if (value.bit_order) {
      writer.attribute(xb::qname{"", "bit-order"},
                       std::string(to_string(*value.bit_order)));
    }
    if (value.selector) {
      writer.start_element(xb::qname{"http://xb.dev/encoding", "selector"});
      write_selector_type(*value.selector, writer);
      writer.end_element();
    }
    for (const auto& choice_item : value.choice) {
      std::visit(
          [&](const auto& v) {
            using T = std::decay_t<decltype(v)>;
            if constexpr (std::is_same_v<T, field_type>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "field"});
              write_field_type(v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T, padding_field_type>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "padding"});
              write_padding_field_type(v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T, constant_type>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "constant"});
              write_constant_type(v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T, wire_field_type>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "wire-field"});
              write_wire_field_type(v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T,
                                                std::unique_ptr<group_type>>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "group"});
              write_group_type(*v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T,
                                                std::unique_ptr<choice_type>>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "choice"});
              write_choice_type(*v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T, length_type>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "length"});
              write_length_type(v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T, discriminant_type>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "discriminant"});
              write_discriminant_type(v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T, save_position_type>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "save-position"});
              write_save_position_type(v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T, computed_field_type>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "computed-field"});
              write_computed_field_type(v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T,
                                                std::unique_ptr<repeat_type>>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "repeat"});
              write_repeat_type(*v, writer);
              writer.end_element();
            }
          },
          choice_item);
    }
    if (value.extensions) {
      writer.start_element(xb::qname{"http://xb.dev/encoding", "extensions"});
      write_extensions_type(*value.extensions, writer);
      writer.end_element();
    }
  }

  inline encoding_type
  read_encoding_type(xb::xml_reader& reader) {
    encoding_type result;
    {
      auto attr_val__ =
          reader.attribute_value(xb::qname{"", "target-namespace"});
      if (!attr_val__.empty()) {
        result.target_namespace = xb::parse<std::string>(attr_val__);
      }
    }
    {
      auto attr_val__ = reader.attribute_value(xb::qname{"", "target-schema"});
      if (!attr_val__.empty()) {
        result.target_schema = xb::parse<std::string>(attr_val__);
      }
    }
    auto start_depth = reader.depth();
    while (reader.read()) {
      if (reader.node_type() == xb::xml_node_type::end_element &&
          reader.depth() == start_depth)
        break;
      if (reader.node_type() != xb::xml_node_type::start_element) continue;
      auto& name = reader.name();
      if (name == xb::qname{"http://xb.dev/encoding", "defaults"}) {
        result.defaults = read_defaults_type(reader);
      } else if (name == xb::qname{"http://xb.dev/encoding", "import"}) {
        result.import.push_back(read_import_type(reader));
      } else if (name == xb::qname{"http://xb.dev/encoding", "framing"}) {
        result.choice.push_back(read_framing_type(reader));
      } else if (name == xb::qname{"http://xb.dev/encoding", "frame-stack"}) {
        result.choice.push_back(read_frame_stack_type(reader));
      } else if (name == xb::qname{"http://xb.dev/encoding", "message"}) {
        result.choice.push_back(read_message_type(reader));
      } else {
        xb::skip_element(reader);
      }
    }
    return result;
  }

  inline void
  write_encoding_type(const encoding_type& value, xb::xml_writer& writer) {
    if (value.target_namespace) {
      writer.attribute(xb::qname{"", "target-namespace"},
                       xb::format(*value.target_namespace));
    }
    if (value.target_schema) {
      writer.attribute(xb::qname{"", "target-schema"},
                       xb::format(*value.target_schema));
    }
    if (value.defaults) {
      writer.start_element(xb::qname{"http://xb.dev/encoding", "defaults"});
      write_defaults_type(*value.defaults, writer);
      writer.end_element();
    }
    for (const auto& item : value.import) {
      writer.start_element(xb::qname{"http://xb.dev/encoding", "import"});
      write_import_type(item, writer);
      writer.end_element();
    }
    for (const auto& choice_item : value.choice) {
      std::visit(
          [&](const auto& v) {
            using T = std::decay_t<decltype(v)>;
            if constexpr (std::is_same_v<T, framing_type>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "framing"});
              write_framing_type(v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T, frame_stack_type>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "frame-stack"});
              write_frame_stack_type(v, writer);
              writer.end_element();
            } else if constexpr (std::is_same_v<T, message_type>) {
              writer.start_element(
                  xb::qname{"http://xb.dev/encoding", "message"});
              write_message_type(v, writer);
              writer.end_element();
            }
          },
          choice_item);
    }
  }

  inline bool
  validate_choice_type(const choice_type& value) {
    return value.alternative.size() >= 1;
  }

  inline bool
  validate_frame_stack_type(const frame_stack_type& value) {
    return value.layer.size() >= 1;
  }

  inline bool
  validate_enum_map_type(const enum_map_type& value) {
    return value.entry.size() >= 1;
  }

  inline bool
  validate_dimension_type(const dimension_type& value) {
    return value.wire_field.size() >= 1;
  }

} // namespace xb::bes
